<?php

namespace App\Console\Commands;

use App\Models\Agent;
use Illuminate\Console\Command;

class SeedAgentRoster extends Command
{
    protected $signature = 'agents:seed-roster';

    protected $description = 'Seed the agent roster with the 6 core agents (idempotent)';

    public function handle(): int
    {
        $agents = [
            [
                'codename' => 'the_professor',
                'display_name' => 'The Professor',
                'function_area' => 'orchestration',
                'role' => 'Control tower / orchestration',
                'status' => 'active',
                'sort_order' => 0,
                'description' => 'The Professor orchestrates all agent activity — planning, sequencing, and delegating tasks across the fleet. Reads the output of every agent and decides what happens next.',
            ],
            [
                'codename' => 'tokyo',
                'display_name' => 'Tokyo',
                'function_area' => 'mining',
                'role' => 'Lead mining & prospecting',
                'status' => 'active',
                'sort_order' => 1,
                'description' => 'Tokyo hunts for leads across search engines, maps, directories, and social platforms. Mines prospect data for all brands based on mining target config.',
            ],
            [
                'codename' => 'bogota',
                'display_name' => 'Bogotá',
                'function_area' => 'enrichment',
                'role' => 'Enrichment / data transformation',
                'status' => 'active',
                'sort_order' => 2,
                'description' => 'Bogotá enriches raw leads with verified contact data — email addresses, phone numbers, social profiles, and business intelligence. Transforms "new" leads into "enriched" leads.',
            ],
            [
                'codename' => 'nairobi',
                'display_name' => 'Nairobi',
                'function_area' => 'drafting',
                'role' => 'Email drafting & content production',
                'status' => 'active',
                'sort_order' => 3,
                'description' => 'Nairobi drafts relationship-based email sequences following Dale Carnegie principles. Reads brand voice guides and past reply data to write emails that start conversations, not pitch products.',
            ],
            [
                'codename' => 'lisbon',
                'display_name' => 'Lisbon',
                'function_area' => 'triage',
                'role' => 'Reply triage & classification',
                'status' => 'active',
                'sort_order' => 4,
                'description' => 'Lisbon monitors the inbox, classifies every reply into intent categories (interested, not_interested, unsubscribe, bounce, out_of_office), and routes them for action.',
            ],
            [
                'codename' => 'palermo',
                'display_name' => 'Palermo',
                'function_area' => 'research',
                'role' => 'Market-signal research',
                'status' => 'maintenance',
                'sort_order' => 5,
                'description' => 'Palermo researches market signals — trending topics, competitor moves, new mining opportunities — and proposes updates to the mining target config. Behaviour ships in a future work order.',
            ],
        ];

        $count = 0;
        foreach ($agents as $data) {
            Agent::updateOrCreate(
                ['codename' => $data['codename']],
                $data
            );
            $this->info("  Seeded: {$data['display_name']} ({$data['codename']})");
            $count++;
        }

        $this->info("Seeded {$count} agents. Tokens are NOT generated by this command — generate them in Filament /admin/agents.");

        return self::SUCCESS;
    }
}
